### ISSUE TITLE
vyos-1x dependencies problem running build-iso.sh

### ISSUE THREAD

**Issue by lukasbeckerit** [dd010101/vyos-jenkins#44]
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 vyos-1x : Depends: fuse-overlayfs but it is not going to be installed
           Depends: podman (>= 4.9.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
I: Checking if packages required for VyOS image build are installed
I: using build flavors directory data/build-flavors
I: Cleaning the build workspace
I: Setting up additional APT entries
I: Configuring live-build
I: Starting image build
Traceback (most recent call last):
  File "/vyos/./build-vyos-image", line 621, in <module>
    cmd("lb build 2>&1")
  File "/vyos/scripts/image-build/utils.py", line 84, in cmd
    raise OSError(f"Command '{command}' failed")
OSError: Command 'lb build 2>&1' failed
ISO build failed
```

Clean and updated Debian 12 install on VM, all automated scripts from 1 to 8 run without problems.

For further reference here build-iso.sh output [build-iso.log](https://github.com/user-attachments/files/16404999/build-iso.log)

**Comment by dutty5** [comment]
podman is a new package, it's commit just has been merged upstream couple of hours ago. It's yet to be added to the vyos-jenkins repo here. If can't wait, as a workaround you may manually add it to the `jobs/jobs/project-jobs.json`, something like:
```
...
{
    "name": "podman",
    "description": "sagitta-only",
    "gitUrl": "https://github.com/vyos/vyos-build.git",
    "branchRegex": "sagitta",
    "jenkinsfilePath": "packages/podman/Jenkinsfile"
  },
...
```

**Comment by lukasbeckerit** [comment]
Awesome, I was able to add 

```
  {
    "name": "podman",
    "description": "sagitta-only",
    "gitUrl": "https://github.com/vyos/vyos-build.git",
    "branchRegex": "sagitta",
    "jenkinsfilePath": "packages/podman/Jenkinsfile"
  }
```

to the jobs/project-jobs.json, ran 6-provision-project-jobs.sh, then 7-build-project-jobs.sh, then forced the build in Jenkins and after that, was able to run build-iso.sh and the iso was generated.

Thank you for your hard work and contributions. Do you think will be funny to aggregate some more options to select if want to generate iso, cow2, etc? I can try to work on this on my spare time.

**Comment by dd010101** [comment]
Since the fix for podman was merged I added the podman package too. I was waiting for the https://github.com/vyos/vyos-build/pull/721.

> Do you think will be funny to aggregate some more options to select if want to generate iso, cow2, etc? I can try to work on this on my spare time.

Yes, that would be helpful. The build-iso.sh is overall very limited thus more configurable version would be great.
