### ISSUE TITLE
6-provision-project-jobs.sh looped

### ISSUE THREAD

**Issue by ashimov** [dd010101/vyos-jenkins#45]
Hello!In Jenkins all packages is builded but in console i see that packages start build many times
![image](https://github.com/user-attachments/assets/b5de5839-d2e3-4a7b-a22b-ed11458793ba)
![image](https://github.com/user-attachments/assets/3ae985d7-e68e-41fe-9153-24cd70bb9972)
![image](https://github.com/user-attachments/assets/dd67782d-ee4b-44a4-99eb-19e754f1823a)

**Comment by dd010101** [comment]
Are you using latest version of the scripts?

Can you please show the **Build History** of **vyos-strongswan/equuleus** job? You can find it in the detail of **vyos-strongswan/equuleus**, in URL like `http://YOUR_HOST:8080/job/vyos-strongswan/job/equuleus/`. 

Also it would be helpful if you would posted the JSON result of API request of URL `http://YOUR_HOST:8080/job/vyos-strongswan/job/equuleus/api/json?pretty=true`.

**Comment by ashimov** [comment]
I'm using latest version of the scripts
vyos-strongswan/equuleus job is clean,why?)
![image](https://github.com/user-attachments/assets/ba2bdc41-2eb7-4fb7-9447-8f9cfe6b2c69)

**Comment by dd010101** [comment]
Please show the **Status** page as well. Do you see **equuleus** branch there?

Also please post the JSON result of `http://YOUR_HOST:8080/job/vyos-strongswan/job/equuleus/`, replace the YOUR_HOST with address of the build host.

The common reason why Build History is empty:
1) Misconfiguration - like no branch was found.
2) Everything is fine - just the runs are too old or many other runs happened since and thus the runs were expired and purged as process of database maintenance.

**Comment by ashimov** [comment]
![image](https://github.com/user-attachments/assets/17860047-9822-44e8-b28e-00652f3e3674)
http://MY_HOST:8080/job/vyos-strongswan/job/equuleus/
![image](https://github.com/user-attachments/assets/2dcfd8a0-123c-42ab-badb-883022ad1c7b)

**Comment by dd010101** [comment]
Seems the indexing of the job failed. Thus there is no branch to be found and this results in infinite loop.

The error you posted:

```
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 8061 bytes of body are still expected
Receiving objects: 85% (58242/68519), 18.30 MiB | 445.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

This is issue of GitHub servers and/or network connection. You can retry the build manually via **Scan Multibranch Pipeline Now** and see if that succeeds.
