### ISSUE TITLE
Does the build will pull newly merged code?

### ISSUE THREAD

**Issue by MaurUppi** [dd010101/vyos-jenkins#55]
Hi there

It is not an issue, but I am trying to understand that. Will Jenkins pull and auto-build with [vyos-1x](https://github.com/vyos/vyos-1x), given that some PRs have been merged since 1.4LTS was announced? 
thanks~~

**Comment by dd010101** [comment]
Yes, if the Jenkins runs then it should automatically eventually do it by itself. You can also force the build with Build now in the Jenkins for given branch. Every build fetches fresh copy of the repository thus includes all new changes.
