### ISSUE TITLE
build vyos-xe-guest-utilities_sagitta broken

### ISSUE THREAD

**Issue by asmc** [dd010101/vyos-jenkins#61]
![CleanShot 2024-12-07 at 14 33 54@2x](https://github.com/user-attachments/assets/e0eda1a3-0211-460c-b835-02a4ba1415fe)
![CleanShot 2024-12-07 at 14 35 08@2x](https://github.com/user-attachments/assets/c421e916-ce1a-4fd5-a8c7-d545ce67b8fd)

**Comment by dutty5** [comment]
Try this solution: https://github.com/dd010101/vyos-jenkins/issues/57#issuecomment-2510019920

**Comment by asmc** [comment]
thanks for reply
I've changed that lib as you can see
![CleanShot 2024-12-08 at 15 00 57@2x](https://github.com/user-attachments/assets/516b4539-e692-472f-87e7-f040cc8cb469)
but another error happend when I build it alone or from 1-xx to 7-xx.sh 
![CleanShot 2024-12-08 at 14 59 17@2x](https://github.com/user-attachments/assets/be964e32-e60e-4128-956a-afd4e91af927)

**Comment by dd010101** [comment]
For the Jenkins Global Library I added automated check/fix in step 2 and 6, thus to fix it just rerun step 2 or 6 (introduced in https://github.com/dd010101/vyos-jenkins/commit/c14506de0ed491b414422e7e667865823653af01).

>  but another error happend when I build it alone or from 1-xx to 7-xx.sh

It complains that sagitta vyos build container isn't available. Try to manually build the vyos-build-container job in Jenkins, for the sagitta branch. This will rebuild the container.

**Comment by asmc** [comment]
I tried to build vyos-build-container some times, but it also failed
![CleanShot 2024-12-08 at 15 56 58@2x](https://github.com/user-attachments/assets/7964ea0e-4816-4d5e-91ca-3c044502bc51)

thanks for replay

**Comment by dd010101** [comment]
Yep, fails for me too, looks like recent development. The OPAM package was changed. I cherry picked the https://github.com/vyos/vyos-build/pull/854 and this fixes the issue.

Try to build vyos-build-container again, now it should work. I tried to build the vyos-build-container for both sagitta and equuleus and with the fix both were successful.

**Comment by asmc** [comment]
I think I opened magic box, lol
![CleanShot 2024-12-08 at 17 38 37@2x](https://github.com/user-attachments/assets/8fc20df3-b557-4a80-9047-796cfa441c1a)

**Comment by dd010101** [comment]
Both netfilter and vyos-xe-guest-utilities of sagitta work for me just fine.

Did the vyos-build-container of sagitta completed successfully? What does the log of vyos-build-container/sagitta say? I have no idea how could other packages build if you have this error, this seems like no package should be build-able, maybe the other packages were built previously?

**Comment by asmc** [comment]
thanks for known both working,I will reinstall a vm to build

**Comment by asmc** [comment]
![CleanShot 2024-12-08 at 18 38 49@2x](https://github.com/user-attachments/assets/e06e882d-6b18-47d8-b04b-ddcef1b09376)
its just working, I tried to build again, after waiting a few minuts
